[package]
name = "ynk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bunt = "0.2.8"
chrono = "0.4.31"
clap = { version = "4.4.16", features = ["derive"] }
dirs = "5.0.1"
futures = "0.3.30"
hashbrown = "0.14.3"
ignore = "0.4.22"
inquire = "0.6"
rusqlite = { version = "0.30.0", features = ["bundled"] }
sea-query = "0"
tokio = { version = "1.35.1", features = ["full"] }
